name: Deploy Vite Frontend to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20   # Vite requires Node 20+

      # Install dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: ./products

      # Build Vite frontend
      - name: Build Vite frontend
        run: npm run build
        working-directory: ./products

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: npm run deploy
        working-directory: ./products
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
