name: Deploy Vite Frontend to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20   # Vite requires Node 20+

      - name: Install dependencies
        run: npm ci
        working-directory: ./Rideify_frontend

      - name: Build Vite frontend
        run: npm run build
        working-directory: ./Rideify_frontend

      - name: Deploy to GitHub Pages
        run: npm run deploy
        working-directory: ./Rideify_frontend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
