name: Deploy Vite Frontend to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('products/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci
        working-directory: ./products

      - name: Build Vite frontend
        run: npm run build
        working-directory: ./products

      - name: Deploy to GitHub Pages
        run: npm run deploy
        working-directory: ./products
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
